- name: My first play
  hosts: electra
  tasks:

  - name: Create group
    group:
      name: "ssl_group"
      state: present

  - name: Creating users "electra" without admin access
    user:
      name: electra
      password: ''
      group: "ssl_group"
      shell: /bin/bash

  - name: "Add nodejs apt key"
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_18.x focal main"
      state: present
      update_cache: yes

  - name: Install required packages
    apt:
      name: 
        - nodejs
        - chromium-browser
        - libnss3
        - libharfbuzz-bin
        - libharfbuzz-dev
        - ca-certificates
        - fonts-freefont-ttf
        - libatk1.0-0 
        - libatk-bridge2.0-0 
        - libcups2 
        - libxkbcommon-x11-0 
        - libxcomposite1 
        - libxdamage1 
        - libxfixes3 
        - libxrandr2 
        - libgbm1 
        - libpango-1.0-0 
        - libcairo2
        - libasound2
      state: latest


  - name: Install PM2 NodeJS Process manager
    npm: name=pm2 global=yes

  - name: Forward port 80 to 8080
    ansible.builtin.iptables:
      table: nat
      chain: PREROUTING
      in_interface: eth0
      protocol: tcp
      match: tcp
      destination_port: 80
      jump: REDIRECT
      to_ports: 8080
      comment: Redirect web traffic to port 8080
    become: yes

  - name: Forward port 443 to 8443
    ansible.builtin.iptables:
      table: nat
      chain: PREROUTING
      in_interface: eth0
      protocol: tcp
      match: tcp
      destination_port: 443
      jump: REDIRECT
      to_ports: 8443
      comment: Redirect ssl web traffic to port 8443
    become: yes

  - name: Install Python 3.12
    apt:
      name: python3.12
      state: present
      update_cache: yes

  - name: Ensure /usr/bin/python3 alternative exists
    command: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1
    become: yes

  - name: Update alternatives to make Python 3.12 the default
    alternatives:
      name: python3
      path: /usr/bin/python3.12
      priority: 2
      state: present

  - name: Verify Python 3.12 installation
    command: python3 --version
    register: python_version

  - name: Display Python version
    debug:
      msg: "Installed Python version is {{ python_version.stdout }}"