- name: My first play
  hosts: electra

  vars_files:
    - secrets.yaml

  tasks:

  - name: Git checkout electra
    become: true
    become_user: electra
    ansible.builtin.git:
      repo: 'https://github.com/freegroup/electra.git'
      dest: /home/electra/server
      force: true
      update: true

  - name: Install packages in /author
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/author

  - name: Install packages in /brains
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/brains

  - name: Install packages in /simulator
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/simulator

  - name: Install packages in /common
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/common

  - name: Install packages in /designer
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/designer

  - name: Install packages in /home
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/home

  - name: Install packages in /ingress
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/ingress

  - name: Install packages in /permissions
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/permissions

  - name: Install packages in /shapes
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/shapes

  - name: Install packages in /sheets
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/sheets

  - name: Install packages in /userinfo
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/userinfo

  - name: Build /home
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/home

  - name: Build /author
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/author

  - name: Build /simulator
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/simulator

  - name: Build /designer
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/designer

  - name: Ensure GITHUB_TOKEN variable in the sesstings.ini
    ansible.builtin.lineinfile:
      path: /home/electra/server/settings.ini
      regexp: '^GITHUB_TOKEN='
      line: GITHUB_TOKEN={{ GITHUB_TOKEN }}

  - name: Run the application via PM2 edosystem configuration
    become: true
    become_user: electra
    command: pm2 restart ./ecosystem.config.js
    args:
      chdir: /home/electra/server/
