- name: My first play
  hosts: electra

  vars_files:
    - deployment_vars.yaml

  tasks:

  - name: Delete old deployment
    file:
      state: absent
      path: /home/electra/server
      
  - name: Git checkout electra
    become: true
    become_user: electra
    ansible.builtin.git:
      repo: 'https://github.com/freegroup/electra.git'
      dest: /home/electra/server
      force: true
      update: true

  - name: Delete local "youtube" directory
    file:
      state: absent
      path: /home/electra/server/youtube

  - name: Delete local "ansible" directory
    file:
      state: absent
      path: /home/electra/server/ansible
    
  - name: Install packages in /author
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/author
    
  - name: Install packages in /legal
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/legal

  - name: Install packages in /brains
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/brains

  - name: Install packages in /simulator
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/simulator

  - name: Install packages in /common
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/common

  - name: Install packages in /designer
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/designer

  - name: Install packages in /home
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/home

  - name: Install packages in /gallery
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/gallery

  - name: Install packages in /gamification
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/gamification

  - name: Install packages in /ingress
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/ingress

  - name: Install packages in /permissions
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/permissions

  - name: Install packages in /shapes
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/shapes

  - name: Install packages in /sheets
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/sheets

  - name: Install packages in /userinfo
    become: true
    become_user: electra
    community.general.npm:
      path: /home/electra/server/userinfo

  - name: Build /gallery
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/gallery

  - name: Build /legal
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/legal

  - name: Build /home
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/home

  - name: Build /author
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/author

  - name: Build /simulator
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/simulator

  - name: Build /designer
    become: true
    become_user: electra
    command: npm run build
    args:
      chdir: /home/electra/server/designer

  - name: Ensure correct data-directory DATADIR_SHAPES in the settings.ini
    ansible.builtin.lineinfile:
      path: /home/electra/server/settings.ini
      regexp: '^DATADIR_SHAPES='
      line: DATADIR_SHAPES={{ DATADIR_SHAPES }}

  - name: Ensure correct data-directory DATADIR_SHEETS in the settings.ini
    ansible.builtin.lineinfile:
      path: /home/electra/server/settings.ini
      regexp: '^DATADIR_SHEETS='
      line: DATADIR_SHEETS={{ DATADIR_SHEETS }}

  - name: Ensure correct data-directory DATADIR_BRAINS in the settings.ini
    ansible.builtin.lineinfile:
      path: /home/electra/server/settings.ini
      regexp: '^DATADIR_BRAINS='
      line: DATADIR_BRAINS={{ DATADIR_BRAINS }}

  - name: Copy secret file 
    ansible.builtin.copy:
      src: ../secrets.ini
      dest: /home/electra/server/secrets.ini
      owner: electra
      group: ssl_group
      mode: '0600'

  - name: Check for running PM2 processes
    become: true
    become_user: electra
    command: pm2 jlist
    args:
      chdir: /home/electra/server/
    register: pm2_list
    ignore_errors: yes

  - name: Delete all running processes via PM2 if any exist
    become: true
    become_user: electra
    command: pm2 delete all
    args:
      chdir: /home/electra/server/
    when: pm2_list.stdout != '[]'  # Condition to check if the PM2 list is not empty
    ignore_errors: yes

  - name: Run the application via PM2 ecosystem configuration
    become: true
    become_user: electra
    command: pm2 restart ./ecosystem.config.js
    args:
      chdir: /home/electra/server/
