- hosts: electra 

  tasks:
  - name : Install Python Package
    apt: name=python3 update_cache=yes state=latest
  
  - name: ensure nginx is at the latest version
    apt: name=nginx state=latest
  
  - name: Create and Install Cert certbot
    command: "certbot certonly --force-renewal --webroot -w /home/electra/server/ingress/public -d electra.academy -d www.electra.academy -m a.herz@freegroup.de --agree-tos --expand --noninteractive --redirect"

  - name: Recursively change ownership of a directory
    ansible.builtin.file:
      path: /etc/letsencrypt
      state: directory
      recurse: yes
      group: ssl_group
      mode: g=rX

  - name: Restart 'ingress' Node.js application with PM2
    command: pm2 restart ingress
    become: true
    become_user: electra
    args:
      chdir: /home/electra/server/
