- hosts: electra 

  tasks:
  - name : Install Python Package
    apt: name=python3 update_cache=yes state=latest

  - name: Create and Install Cert certbot
    command: "certbot certonly --webroot -w /home/electra/server/ingress/public -d  www.electra.academy -m a.herz@freegroup.de --agree-tos --noninteractive --redirect"

  - name: Recursively change ownership of a directory
    ansible.builtin.file:
      path: /etc/letsencrypt
      state: directory
      recurse: yes
      group: ssl_group
